# Generated by Django 4.2.30 on 2026-07-10 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mmessage',
            old_name='receeiver',
            new_name='receiver',
        ),
    ]
