# Generated by Django 4.2.30 on 2026-07-10 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connection1', '0002_rename_receeiver_mmessage_receiver'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='mmessage',
            new_name='Message',
        ),
    ]
