# Generated by Django 6.0.3 on 2026-05-04 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsz', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student',
            new_name='students',
        ),
    ]
