# Generated by Django 4.2.11 on 2026-04-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('email', models.EmailField(default='Innow8', max_length=254, unique=True)),
                ('company', models.CharField(max_length=25)),
                ('city', models.CharField(default='unknown', max_length=10)),
            ],
        ),
    ]
