# Generated by Django 6.0.3 on 2026-04-09 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='Untitled', max_length=200),
        ),
    ]
