# Generated by Django 6.0.3 on 2026-04-15 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publishing_year',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
